# Pipeline for azure-web-extensions

trigger:
- master

variables:
  BootsDir: $(System.DefaultWorkingDirectory)\Tasks\Boots

jobs:
- job: build_test_win
  displayName: Build and Test on Windows
  pool: Hosted Windows 2019 with VS2019
  timeoutInMinutes: 60
  cancelTimeoutInMinutes: 5
  steps:
  - task: NodeTool@0
    displayName: install node 10.x
    inputs:
      versionSpec: 10.x

  - task: Npm@1
    displayName: install mocha
    inputs:
      command: custom
      customCommand: install mocha -g

  - task: Npm@1
    displayName: boots - npm install
    inputs:
      command: install
      workingDir: $(BootsDir)

  - script: tsc
    displayName: boots - compile typescript
    workingDirectory: $(BootsDir)

  - script: mocha Tests\suite.js
    displayName: boots - run tests
    workingDirectory: $(BootsDir)

  - script: tfx extension create --manifest-globs vss-extension.json --output-path $(Build.ArtifactStagingDirectory)
    displayName: create tasks extension
    workingDirectory: $(System.DefaultWorkingDirectory)\Tasks

  - task: PublishPipelineArtifact@0
    displayName: upload tasks extension
    inputs:
      artifactName: azp-tasks-extension
      targetPath: $(Build.ArtifactStagingDirectory)
